#!/usr/bin/env python3

from webbot import Browser

def configure_proxy(proxy_host, proxy_port):
    # Adding proxy settings to the webbot Browser
    options = {
        'proxy': {
            'http': f'{proxy_host}:{proxy_port}',
            'https': f'{proxy_host}:{proxy_port}'
        }
    }
    return options

def search_google_with_proxy(proxy_host, proxy_port, search_query):
    proxy_options = configure_proxy(proxy_host, proxy_port)
    web = Browser(browser_options=proxy_options)
    web.go_to('https://www.google.com')
    web.type(search_query, into='Search')
    web.press(web.Key.ENTER)

if __name__ == '__main__':
    proxy_host = 'your_proxy_host'
    proxy_port = 'your_proxy_port'
    search_query = 'hello its me'
    search_google_with_proxy(proxy_host, proxy_port, search_query)
